package org.inwiss.platform.model.ext;

import java.util.ArrayList;
import java.util.List;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;


/**
 * Menu generated by Lingo.
 *
 * @author RD
 */
@JsonIgnoreProperties({ "checked","children" })
public class TreeItemOrg extends LongTreeNode<TreeItemOrg> {
   
    /**
	 * 
	 */
	private static final long serialVersionUID = -4721129509819246740L;

	/** * id. */
    private Long id;

    /** * parent. */
    private TreeItemOrg parent;

    /** * name. */
    private String name;

    /** * theSort. */
    private Integer position;


	/** * qtip. */
    private String qtip;

    /** * iconCls. */
    private String iconCls;

    /** * forward. */
    private String location;

    /** * descn. */
    private String descn;

	private boolean isLeaf = true;

	
	public void setLeaf(boolean isLeaf) {
		this.isLeaf = isLeaf;
	}
	@Override
	public boolean isLeaf() {
		return isLeaf;
	}
	
   
    //protected List<Role> roles = new ArrayList<Role>();

	/** * checked. */
    private boolean checked = false;

    /** * 构造方法. */
    public TreeItemOrg() {
    }

    /** * @return id. */
    public Long getId() {
        return id;
    }

    /** * @param id id. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return parent. */
    public TreeItemOrg getParent() {
        return parent;
    }

    /** * @param parent Menu. */
    public void setParent(TreeItemOrg parent) {
        this.parent = parent;
    }

    /** * @return name. */
    public String getName() {
        return name;
    }

    /** * @param name name. */
    public void setName(String name) {
        this.name = name;
    }

  
    /** * @return qtip. */
    public String getQtip() {
        return qtip;
    }

    /** * @param qtip String. */
    public void setQtip(String qtip) {
        this.qtip = qtip;
    }

    /** * @return iconCls. */
    public String getIconCls() {
        return iconCls;
    }

    /** * @param iconCls icon. */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls;
    }

    /** * @return url. */
    public String getLocation() {
        return location;
    }

    /** * @param url String. */
    public void setLocation(String location) {
        this.location = location;
    }

    /** * @return descn. */
    public String getDescn() {
        return descn;
    }

    /** * @param descn descn. */
    public void setDescn(String descn) {
        this.descn = descn;
    }

    
    /** * @return isChecked. */

    public boolean isChecked() {
        return checked;
    }

    /** * @param checked boolean. */
    public void setChecked(boolean checked) {
        this.checked = checked;
    }
    
    
    public Integer getPosition() {
		return position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}
	
    


	/** * roles. */

   

    /*public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}*/

}
