CREATE USER fee
  IDENTIFIED BY VALUES '42E8C0542CFD769D'
  DEFAULT TABLESPACE TS_FIN_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for fee 
  GRANT IMP_FULL_DATABASE TO fee WITH ADMIN OPTION;
  GRANT CONNECT TO fee WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO fee WITH ADMIN OPTION;
  GRANT DBA TO fee WITH ADMIN OPTION;
  ALTER USER fee DEFAULT ROLE ALL;
  -- 1 System Privilege for fee 
  GRANT UNLIMITED TABLESPACE TO fee WITH ADMIN OPTION;
  -- 1 Tablespace Quota for fee 
  ALTER USER fee QUOTA UNLIMITED ON TS_FIN_DATA;
  ALTER USER fee IDENTIFIED BY "fee";



CREATE USER ETLRESP
  IDENTIFIED BY VALUES '42E8F0542CFF769E'
  DEFAULT TABLESPACE TS_FIN_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for ETLRESP 
  GRANT IMP_FULL_DATABASE TO ETLRESP WITH ADMIN OPTION;
  GRANT CONNECT TO ETLRESP WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO ETLRESP WITH ADMIN OPTION;
  GRANT DBA TO ETLRESP WITH ADMIN OPTION;
  ALTER USER ETLRESP DEFAULT ROLE ALL;
  -- 1 System Privilege for ETLRESP 
  GRANT UNLIMITED TABLESPACE TO ETLRESP WITH ADMIN OPTION;
  -- 1 Tablespace Quota for ETLRESP 
  ALTER USER ETLRESP QUOTA UNLIMITED ON TS_FIN_DATA;
  ALTER USER ETLRESP IDENTIFIED BY "ETLRESP";
