SET DEFINE OFF;
CREATE ROLE FINROLE NOT IDENTIFIED;

GRANT CREATE TYPE TO FINROLE WITH ADMIN OPTION;
GRANT CREATE VIEW TO FINROLE WITH ADMIN OPTION;
GRANT CREATE TABLE TO FINROLE WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO FINROLE WITH ADMIN OPTION;
GRANT CREATE SESSION TO FINROLE WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO FINROLE WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO FINROLE WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO FINROLE WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO FINROLE WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO FINROLE WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO FINROLE WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO FINROLE WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO FINROLE WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO FINROLE WITH ADMIN OPTION;
GRANT DROP ANY DIRECTORY TO FINROLE WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO FINROLE WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO FINROLE WITH ADMIN OPTION;
GRANT FLASHBACK ANY TABLE TO FINROLE WITH ADMIN OPTION;
GRANT SELECT ANY SEQUENCE TO FINROLE WITH ADMIN OPTION;
GRANT CREATE ANY DIRECTORY TO FINROLE WITH ADMIN OPTION;
GRANT CREATE ANY PROCEDURE TO FINROLE WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO FINROLE;
GRANT CREATE PUBLIC SYNONYM TO FINROLE WITH ADMIN OPTION;
GRANT DEBUG CONNECT SESSION TO FINROLE WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO FINROLE WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO FINROLE WITH ADMIN OPTION;
GRANT CONNECT TO FINROLE WITH ADMIN OPTION;
GRANT RESOURCE TO FINROLE WITH ADMIN OPTION;

CREATE TABLESPACE TS_FIN_DATA DATAFILE 
  '/u01/app/oracle/oradata/rdata_fin_01' SIZE 210M AUTOEXTEND ON NEXT 10M MAXSIZE 4096M
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE USER fee
  IDENTIFIED BY VALUES '060799FA2E019588'
  DEFAULT TABLESPACE TS_FIN_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for fee 
  GRANT CONNECT TO fee WITH ADMIN OPTION;
  GRANT DBA TO fee WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO fee WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO fee WITH ADMIN OPTION;
  ALTER USER fee DEFAULT ROLE ALL;
  -- 1 System Privilege for fee 
  GRANT UNLIMITED TABLESPACE TO fee WITH ADMIN OPTION;
  -- 1 Tablespace Quota for fee 
  ALTER USER fee QUOTA UNLIMITED ON TS_FIN_DATA;



  CREATE USER ETLRESP
  IDENTIFIED BY VALUES '56503194E67C1659'
  DEFAULT TABLESPACE TS_INF_DATA
  TEMPORARY TABLESPACE TS_FIN_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ETLRESP 
  GRANT CONNECT TO ETLRESP;
  GRANT RESOURCE TO ETLRESP;
  ALTER USER ETLRESP DEFAULT ROLE ALL;
  -- 22 System Privileges for ETLRESP 
  GRANT ANALYZE ANY TO ETLRESP;
  GRANT DROP ANY SEQUENCE TO ETLRESP WITH ADMIN OPTION;
  GRANT DROP ANY TABLE TO ETLRESP;
  GRANT ALTER ANY PROCEDURE TO ETLRESP;
  GRANT DEBUG CONNECT SESSION TO ETLRESP;
  GRANT CREATE ANY PROCEDURE TO ETLRESP;
  GRANT ALTER ANY SEQUENCE TO ETLRESP WITH ADMIN OPTION;
  GRANT ALTER ANY TABLE TO ETLRESP;
  GRANT CREATE SESSION TO ETLRESP;
  GRANT DEBUG ANY PROCEDURE TO ETLRESP;
  GRANT CREATE ANY VIEW TO ETLRESP;
  GRANT DELETE ANY TABLE TO ETLRESP;
  GRANT UPDATE ANY TABLE TO ETLRESP;
  GRANT INSERT ANY TABLE TO ETLRESP;
  GRANT SELECT ANY DICTIONARY TO ETLRESP;
  GRANT CREATE ANY TABLE TO ETLRESP;
  GRANT EXECUTE ANY PROCEDURE TO ETLRESP;
  GRANT SELECT ANY TABLE TO ETLRESP;
  GRANT CREATE DATABASE LINK TO ETLRESP;
  GRANT SELECT ANY SEQUENCE TO ETLRESP WITH ADMIN OPTION;
  GRANT CREATE ANY SEQUENCE TO ETLRESP WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO ETLRESP;




  CREATE USER FEE
  IDENTIFIED BY VALUES 'B35A5208456326AD'
  DEFAULT TABLESPACE TS_FIN_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for FEE 
  GRANT CONNECT TO FEE WITH ADMIN OPTION;
  GRANT DBA TO FEE WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO FEE WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO FEE WITH ADMIN OPTION;
  ALTER USER FEE DEFAULT ROLE ALL;
  -- 1 System Privilege for FEE 
  GRANT UNLIMITED TABLESPACE TO FEE WITH ADMIN OPTION;
  -- 1 Tablespace Quota for FEE 
  ALTER USER FEE QUOTA UNLIMITED ON TS_FIN_DATA;